### ISSUE TITLE
Can't drag files onto main.py

### ISSUE THREAD

**Issue by RyukoM4701** [Kyuuhachi/Septluxian-Scope#1]
I have no knowledge about python or any other programming language but I don't know if that's even related, just wanted to say.
When you normally drag something over an exe file for an example, they both light up, meaning it's somehow draggable/able to run together even if nothing comes out of them.
That wasn't the case with main.py, I tried moving a .bin file on top of it and no light up, nothing if I let go of the file, I can't seem to make this work. 

Edit1: I think it was the Python installed through Microsoft Store because it started working after I uninstalled that and installed from website.
Edit2: However, I still can't seem to get it to work. I'm dragging a scp file to main.py yet nothing happens. What am I possibly doing wrong?
Edit3: All above was tested with Python 3.12
Edit4: Doesn't work with Python 3.11 either

**Comment by Kyuuhachi** [comment]
Right, should be fixed now. Issue was basically that I only tried it on my local setup and assumed that'd work for everyone. Which, as everyone knows, is a most foolish assumption.
