### ISSUE TITLE
.scp files don't work

### ISSUE THREAD

**Issue by RyukoM4701** [Kyuuhachi/Septluxian-Scope#2]
I have another issue to report. I tried using a couple .scp files from inside the script\en folder but none that I've tried to seem to have worked
``C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\mp0402.scp → Traceback (most recent call last):
  File "C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\main.py", line 32, in __main__
    outfile = process_file(make_output, insns, file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\main.py", line 70, in process_file
    csv.writer(f).writerows(zip(lines[0::2], lines[1::2]))
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
'charmap' codec can't encode characters in position 0-6: character maps to <undefined>``

**Comment by Kyuuhachi** [comment]
Right, forgot that the encoding doesn't default to utf-8 on Windows... Try this.

**Comment by RyukoM4701** [comment]
It still doesn't work... I get this, I don't know if it's the same as above
``C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\mp0402.scp → Traceback (most recent call last):
  File "C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\main.py", line 32, in __main__
    outfile = process_file(make_output, insns, file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RyukoM4701\Desktop\YSTools\Septluxian-Scope-main\main.py", line 70, in process_file
    csv.writer(f).writerows(zip(lines[0::2], lines[1::2]))
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
'charmap' codec can't encode characters in position 0-6: character maps to <undefined>``

It seems like the script has issues reading Japanese I think but then again, I don't know anything about coding so don't mind me. I also have another question to ask which is not exactly related to the script aswell. Should I do it under here or would you like to discuss it in somewhere like Discord?

**Comment by Kyuuhachi** [comment]
Oh for Aidios' sake — seems there was another place where I forgot to set it to utf-8... Fuckin' python, man. Should be fixed now, I hope. Probably.

Yeah discord is fine. I personally like discussing such things on the [modding discord](https://discord.gg/tStv2UU2), to keep things publicly available, but dm is ok too if you prefer.

**Comment by RyukoM4701** [comment]
Works flawless now, thank you so much.
