### ISSUE TITLE
Falcom Fans

### ISSUE THREAD

**Issue by HarvestWinter** [Kyuuhachi/Septluxian-Scope#3]
Hello, sorry for disturbing you. Can you make your tools Septluxian Scope compatible with Nayuta no Kiseki (Addendum) PSP version?

And can you make other tools to decompiler Ys Seven PSP version too? Thank you very much.

**Comment by Kyuuhachi** [comment]
Iirc Nayuta PSP has the same format as on PC, so Septluxian Scope should work already. Is this not the case?

Ys 7 uses the same format as 8 and Nayuta, so decompiling that wouldn't be overly difficult (same for Ys Vs Trails btw). Problem is the table of instruction names, which I was able to scrape from the .exe for 8 and Nayuta but couldn't find any for 7. I could make a barebones table with only the parts needed to decompile at all, but leave the command names blank. Would that be an ok compromise?

Also gonna try transferring this issue to the relevant repo, hope that works.

**Comment by HarvestWinter** [comment]
Yes, it is true that both have the same format. But after I tried it, only the PC version was successful while the PSP version failed. Could you fix it if you had time? Sorry if I ask for the PSP version, but the problem is that in my case, many people prefer to play the PSP version because it can be played via mobile with an emulator.

![Test](https://github.com/Kyuuhachi/Septluxian-Scope/assets/137517761/2166c4b6-c4ce-4730-888f-715dcbb772ca)

**Comment by HarvestWinter** [comment]
I don't really know about this. But this is the result of YS7 PSP. Sorry, I can only give you this.

![TEST](https://github.com/Kyuuhachi/Septluxian-Scope/assets/137517761/8de43e6f-c277-4071-8081-f27dd9deb59b)

**Comment by Kyuuhachi** [comment]
I can't replicate the issue with Nayuta PSP — `./main.py nayuta/PSP_GAME/USRDIR/script/mp_0119.bin` works fine. Working on the ys7 table rn.

**Comment by Kyuuhachi** [comment]
Ys 7 table added. It's extremely similar to 8's. However the Scope can't automatically determine whether a script is Nayuta or Ys 7, so you have to run it with `-i ys7`.

**Comment by HarvestWinter** [comment]
Hello, sorry for disturbing you again. I've tried several times before coming here again. Can you check mp_1200 from YS7 PSP version? When unpacking it succeeds but when repacking it fails, it's different from mp_1301. Could you fix it if you had time?

I've also tried the PC version of YS7. But it turns out that all the text has been moved to lang\en\textscript.dbin. So they don't use mp_????.bin files anymore.

Oh, and do you have any other contacts besides here? Thank You.

**Comment by Kyuuhachi** [comment]
I don't have the ys7 psp files, so I can't do much there. Perhaps you could send it to me on discord (same name as here)?

The Scope does support dbin files.

**Comment by Kyuuhachi** [comment]
Turns out the issue with the Nayuta scripts was because the script was edited with other tools. Made my parser more lenient to deal with this.
